version: 1.0.{build}-{branch}

image: Visual Studio 2015

environment:
  APPVEYOR_RDP_PASSWORD: fixm3-wtf
  RUBY_VERSION: 23-x64
  #PATH: C:\Ruby%RUBY_VERSION%\bin;C:\Ruby23-x64\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH%
  PATH: c:\Ruby%RUBY_VERSION%\DevKit\mingw\bin;C:\Ruby%RUBY_VERSION%\bin;C:\Ruby%RUBY_VERSION%\DevKit\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1;%PATH% 
build: off

before_build:
  - ruby -v
  - make -v

build_script:
  - cd C:\projects\oj\ext\oj
  - ruby extconf.rb
  - make

